flags.country_flag_mapping.*:
  type: config_entity
  label: 'Flag Mapping'
  mapping:
    source:
      type: string
      label: 'Country code'
    uuid:
      type: string
      label: 'UUID'
    flag:
      type: string
      label: 'Target territory flag'

flags.language_flag_mapping.*:
  type: config_entity
  label: 'Flag Mapping'
  mapping:
    source:
      type: string
      label: 'Language code'
    uuid:
      type: string
      label: 'UUID'
    info:
      type: string
      label: 'Info'
    flag:
      type: string
      label: 'Target territory flag'
